# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "03fdd7d0352cc3b1184544f7e2c783be"
name = "reviewapp"
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_themes,write_products,write_themes"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[app_proxy]
url = "https://balwan-singh-rajput-itg.myshopify.com"
subpath = "review"
prefix = "apps"
